Jul 16 06:25:01 ip-172-31-92-31 rsyslogd:  [origin software="rsyslogd" swVersion="8.32.0" x-pid="842" x-info="http://www.rsyslog.com"] rsyslogd was HUPed
Jul 16 06:35:46 ip-172-31-92-31 systemd-networkd[690]: eth0: Configured
Jul 16 06:35:46 ip-172-31-92-31 systemd-timesyncd[539]: Network configuration changed, trying to establish connection.
Jul 16 06:35:47 ip-172-31-92-31 systemd-timesyncd[539]: Synchronized to time server 91.189.94.4:123 (ntp.ubuntu.com).
Jul 16 07:05:47 ip-172-31-92-31 systemd-networkd[690]: eth0: Configured
Jul 16 07:05:47 ip-172-31-92-31 systemd-timesyncd[539]: Network configuration changed, trying to establish connection.
Jul 16 07:05:47 ip-172-31-92-31 systemd-timesyncd[539]: Synchronized to time server 91.189.94.4:123 (ntp.ubuntu.com).
Jul 16 07:08:08 ip-172-31-92-31 systemd[1]: Starting Message of the Day...
Jul 16 07:08:14 ip-172-31-92-31 50-motd-news[1847]:  * Super-optimized for small spaces - read how we shrank the memory
Jul 16 07:08:14 ip-172-31-92-31 50-motd-news[1847]:    footprint of MicroK8s to make it the smallest full K8s around.
Jul 16 07:08:14 ip-172-31-92-31 50-motd-news[1847]:    https://ubuntu.com/blog/microk8s-memory-optimisation
Jul 16 07:08:14 ip-172-31-92-31 systemd[1]: Started Message of the Day.
Jul 16 07:17:01 ip-172-31-92-31 CRON[1924]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jul 16 07:35:48 ip-172-31-92-31 systemd-networkd[690]: eth0: Configured
Jul 16 07:35:48 ip-172-31-92-31 systemd-timesyncd[539]: Network configuration changed, trying to establish connection.
Jul 16 07:35:48 ip-172-31-92-31 systemd-timesyncd[539]: Synchronized to time server 91.189.94.4:123 (ntp.ubuntu.com).
Jul 16 08:04:08 ip-172-31-92-31 systemd[1]: Starting Daily apt download activities...
Jul 16 08:04:08 ip-172-31-92-31 systemd[1]: Started Daily apt download activities.
Jul 16 08:05:47 ip-172-31-92-31 systemd-networkd[690]: eth0: Configured
Jul 16 08:05:47 ip-172-31-92-31 systemd-timesyncd[539]: Network configuration changed, trying to establish connection.
Jul 16 08:05:47 ip-172-31-92-31 systemd-timesyncd[539]: Synchronized to time server 91.189.94.4:123 (ntp.ubuntu.com).
Jul 16 08:17:01 ip-172-31-92-31 CRON[2063]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jul 16 08:35:47 ip-172-31-92-31 systemd-networkd[690]: eth0: Configured
Jul 16 08:35:47 ip-172-31-92-31 systemd-timesyncd[539]: Network configuration changed, trying to establish connection.
Jul 16 08:35:48 ip-172-31-92-31 systemd-timesyncd[539]: Synchronized to time server 91.189.94.4:123 (ntp.ubuntu.com).
Jul 16 09:05:47 ip-172-31-92-31 systemd-networkd[690]: eth0: Configured
Jul 16 09:05:47 ip-172-31-92-31 systemd-timesyncd[539]: Network configuration changed, trying to establish connection.
Jul 16 09:05:47 ip-172-31-92-31 systemd-timesyncd[539]: Synchronized to time server 91.189.94.4:123 (ntp.ubuntu.com).
Jul 16 09:17:01 ip-172-31-92-31 CRON[2131]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jul 16 09:35:47 ip-172-31-92-31 systemd-networkd[690]: eth0: Configured
Jul 16 09:35:47 ip-172-31-92-31 systemd-timesyncd[539]: Network configuration changed, trying to establish connection.
Jul 16 09:35:47 ip-172-31-92-31 systemd-timesyncd[539]: Synchronized to time server 91.189.94.4:123 (ntp.ubuntu.com).
Jul 16 10:00:55 ip-172-31-92-31 snapd[855]: storehelpers.go:551: cannot refresh: snap has no updates available: "amazon-ssm-agent", "core18", "snapd"
Jul 16 10:00:55 ip-172-31-92-31 snapd[855]: autorefresh.go:513: auto-refresh: all snaps are up-to-date
Jul 16 10:05:47 ip-172-31-92-31 systemd-networkd[690]: eth0: Configured
Jul 16 10:05:47 ip-172-31-92-31 systemd-timesyncd[539]: Network configuration changed, trying to establish connection.
Jul 16 10:05:47 ip-172-31-92-31 systemd-timesyncd[539]: Synchronized to time server 91.189.94.4:123 (ntp.ubuntu.com).
Jul 16 10:17:01 ip-172-31-92-31 CRON[2199]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jul 16 10:35:47 ip-172-31-92-31 systemd-networkd[690]: eth0: Configured
Jul 16 10:35:47 ip-172-31-92-31 systemd-timesyncd[539]: Network configuration changed, trying to establish connection.
Jul 16 10:35:47 ip-172-31-92-31 systemd-timesyncd[539]: Synchronized to time server 91.189.94.4:123 (ntp.ubuntu.com).
Jul 16 11:05:47 ip-172-31-92-31 systemd-networkd[690]: eth0: Configured
Jul 16 11:05:47 ip-172-31-92-31 systemd-timesyncd[539]: Network configuration changed, trying to establish connection.
Jul 16 11:05:47 ip-172-31-92-31 systemd-timesyncd[539]: Synchronized to time server 91.189.94.4:123 (ntp.ubuntu.com).
Jul 16 11:17:01 ip-172-31-92-31 CRON[2266]: (root) CMD (   cd / && run-parts --report /etc/cron.hourly)
Jul 16 11:35:47 ip-172-31-92-31 systemd-networkd[690]: eth0: Configured
Jul 16 11:35:47 ip-172-31-92-31 systemd-timesyncd[539]: Network configuration changed, trying to establish connection.
Jul 16 11:35:47 ip-172-31-92-31 systemd-timesyncd[539]: Synchronized to time server 91.189.94.4:123 (ntp.ubuntu.com).
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]: [2021-07-16 11:43:52,092] ERROR in app: Exception on / [GET]
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]: Traceback (most recent call last):
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     cursor, statement, parameters, context
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     cursor.execute(statement, parameters)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 148, in execute
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     result = self._query(query)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 310, in _query
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     conn.query(q)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/pymysql/connections.py", line 548, in query
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/pymysql/connections.py", line 775, in _read_query_result
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     result.read()
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1156, in read
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     first_packet = self.connection._read_packet()
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/pymysql/connections.py", line 692, in _read_packet
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     packet_header = self._read_bytes(4)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/pymysql/connections.py", line 749, in _read_bytes
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     CR.CR_SERVER_LOST, "Lost connection to MySQL server during query"
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]: pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]: The above exception was the direct cause of the following exception:
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]: Traceback (most recent call last):
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/application.py", line 52, in homepage
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     user_id =  current_user.get_user_id()
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/werkzeug/local.py", line 422, in __get__
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     obj = instance._get_current_object()
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/werkzeug/local.py", line 544, in _get_current_object
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     return self.__local()  # type: ignore
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask_login/utils.py", line 26, in <lambda>
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     current_user = LocalProxy(lambda: _get_user())
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask_login/utils.py", line 346, in _get_user
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     current_app.login_manager._load_user()
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask_login/login_manager.py", line 318, in _load_user
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     user = self._user_callback(user_id)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/application.py", line 68, in load_user
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     return User.query.get(user_id)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "<string>", line 2, in get
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     return fn(*args, **kwargs)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 933, in get
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     return self._get_impl(ident, loading.load_on_pk_identity)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 945, in _get_impl
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     execution_options=self._execution_options,
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2843, in _get_impl
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     load_options=load_options,
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 535, in load_on_pk_identity
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     bind_arguments=bind_arguments,
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     result = conn._execute_20(statement, params or {}, execution_options)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     return meth(self, args_10style, kwargs_10style, execution_options)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     self, multiparams, params, execution_options
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1461, in _execute_clauseelement
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     cache_hit=cache_hit,
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     e, statement, parameters, cursor, context
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1995, in _handle_dbapi_exception
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     sqlalchemy_exception, with_traceback=exc_info[2], from_=e
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     raise exception
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1771, in _execute_context
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     cursor, statement, parameters, context
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     cursor.execute(statement, parameters)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 148, in execute
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     result = self._query(query)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/pymysql/cursors.py", line 310, in _query
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     conn.query(q)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/pymysql/connections.py", line 548, in query
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/pymysql/connections.py", line 775, in _read_query_result
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     result.read()
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/pymysql/connections.py", line 1156, in read
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     first_packet = self.connection._read_packet()
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/pymysql/connections.py", line 692, in _read_packet
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     packet_header = self._read_bytes(4)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/pymysql/connections.py", line 749, in _read_bytes
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     CR.CR_SERVER_LOST, "Lost connection to MySQL server during query"
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]: sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]: [SQL: SELECT users.email AS users_email, users.id AS users_id, users.password AS users_password
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]: FROM users
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]: WHERE users.email = %(pk_1)s]
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]: [parameters: {'pk_1': 'gordondavidf@gmail.com'}]
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]: (Background on this error at: http://sqlalche.me/e/14/e3q8)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]: During handling of the above exception, another exception occurred:
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]: Traceback (most recent call last):
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask/app.py", line 2070, in wsgi_app
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     response = self.full_dispatch_request()
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask/app.py", line 1515, in full_dispatch_request
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     rv = self.handle_user_exception(e)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask/app.py", line 1513, in full_dispatch_request
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     rv = self.dispatch_request()
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask/app.py", line 1499, in dispatch_request
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/application.py", line 62, in homepage
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     return render_template('login.html', form=form, form2=form2)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask/templating.py", line 146, in render_template
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     ctx.app.update_template_context(context)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask/app.py", line 756, in update_template_context
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     context.update(func())
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask_login/utils.py", line 379, in _user_context_processor
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     return dict(current_user=_get_user())
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask_login/utils.py", line 346, in _get_user
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     current_app.login_manager._load_user()
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask_login/login_manager.py", line 318, in _load_user
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     user = self._user_callback(user_id)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/application.py", line 68, in load_user
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     return User.query.get(user_id)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "<string>", line 2, in get
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     return fn(*args, **kwargs)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 933, in get
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     return self._get_impl(ident, loading.load_on_pk_identity)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 945, in _get_impl
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     execution_options=self._execution_options,
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2843, in _get_impl
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     load_options=load_options,
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 535, in load_on_pk_identity
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     bind_arguments=bind_arguments,
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     result = conn._execute_20(statement, params or {}, execution_options)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     return meth(self, args_10style, kwargs_10style, execution_options)
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     self, multiparams, params, execution_options
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1461, in _execute_clauseelement
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     cache_hit=cache_hit,
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1668, in _execute_context
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     conn = self._revalidate_connection()
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 560, in _revalidate_connection
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     self._invalid_transaction()
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 540, in _invalid_transaction
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]:     code="8s2b",
Jul 16 11:43:52 ip-172-31-92-31 gunicorn[822]: sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back. (Background on this error at: http://sqlalche.me/e/14/8s2b)
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]: [2021-07-16 11:44:00,932] ERROR in app: Exception on / [GET]
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]: Traceback (most recent call last):
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/application.py", line 52, in homepage
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     user_id =  current_user.get_user_id()
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/werkzeug/local.py", line 422, in __get__
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     obj = instance._get_current_object()
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/werkzeug/local.py", line 544, in _get_current_object
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     return self.__local()  # type: ignore
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask_login/utils.py", line 26, in <lambda>
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     current_user = LocalProxy(lambda: _get_user())
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask_login/utils.py", line 346, in _get_user
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     current_app.login_manager._load_user()
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask_login/login_manager.py", line 318, in _load_user
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     user = self._user_callback(user_id)
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/application.py", line 68, in load_user
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     return User.query.get(user_id)
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "<string>", line 2, in get
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     return fn(*args, **kwargs)
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 933, in get
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     return self._get_impl(ident, loading.load_on_pk_identity)
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 945, in _get_impl
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     execution_options=self._execution_options,
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2843, in _get_impl
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     load_options=load_options,
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 535, in load_on_pk_identity
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     bind_arguments=bind_arguments,
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     result = conn._execute_20(statement, params or {}, execution_options)
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     return meth(self, args_10style, kwargs_10style, execution_options)
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     self, multiparams, params, execution_options
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1461, in _execute_clauseelement
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     cache_hit=cache_hit,
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1668, in _execute_context
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     conn = self._revalidate_connection()
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 560, in _revalidate_connection
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     self._invalid_transaction()
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 540, in _invalid_transaction
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     code="8s2b",
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]: sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back. (Background on this error at: http://sqlalche.me/e/14/8s2b)
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]: During handling of the above exception, another exception occurred:
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]: Traceback (most recent call last):
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask/app.py", line 2070, in wsgi_app
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     response = self.full_dispatch_request()
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask/app.py", line 1515, in full_dispatch_request
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     rv = self.handle_user_exception(e)
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask/app.py", line 1513, in full_dispatch_request
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     rv = self.dispatch_request()
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask/app.py", line 1499, in dispatch_request
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/application.py", line 62, in homepage
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     return render_template('login.html', form=form, form2=form2)
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask/templating.py", line 146, in render_template
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     ctx.app.update_template_context(context)
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask/app.py", line 756, in update_template_context
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     context.update(func())
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask_login/utils.py", line 379, in _user_context_processor
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     return dict(current_user=_get_user())
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask_login/utils.py", line 346, in _get_user
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     current_app.login_manager._load_user()
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/flask_login/login_manager.py", line 318, in _load_user
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     user = self._user_callback(user_id)
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/application.py", line 68, in load_user
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     return User.query.get(user_id)
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "<string>", line 2, in get
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     return fn(*args, **kwargs)
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 933, in get
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     return self._get_impl(ident, loading.load_on_pk_identity)
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 945, in _get_impl
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     execution_options=self._execution_options,
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2843, in _get_impl
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     load_options=load_options,
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 535, in load_on_pk_identity
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     bind_arguments=bind_arguments,
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1689, in execute
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     result = conn._execute_20(statement, params or {}, execution_options)
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     return meth(self, args_10style, kwargs_10style, execution_options)
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     self, multiparams, params, execution_options
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1461, in _execute_clauseelement
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     cache_hit=cache_hit,
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1668, in _execute_context
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     conn = self._revalidate_connection()
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 560, in _revalidate_connection
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     self._invalid_transaction()
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:   File "/home/ubuntu/var/www/campfire/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 540, in _invalid_transaction
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]:     code="8s2b",
Jul 16 11:44:00 ip-172-31-92-31 gunicorn[822]: sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back. (Background on this error at: http://sqlalche.me/e/14/8s2b)
Jul 16 11:44:15 ip-172-31-92-31 systemd[1]: Created slice User Slice of ubuntu.
Jul 16 11:44:15 ip-172-31-92-31 systemd[1]: Starting User Manager for UID 1000...
Jul 16 11:44:15 ip-172-31-92-31 systemd[1]: Started Session 12 of user ubuntu.
Jul 16 11:44:15 ip-172-31-92-31 systemd[2310]: Listening on GnuPG network certificate management daemon.
Jul 16 11:44:15 ip-172-31-92-31 systemd[2310]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Jul 16 11:44:15 ip-172-31-92-31 systemd[2310]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Jul 16 11:44:15 ip-172-31-92-31 systemd[2310]: Listening on GnuPG cryptographic agent and passphrase cache.
Jul 16 11:44:15 ip-172-31-92-31 systemd[2310]: Reached target Timers.
Jul 16 11:44:15 ip-172-31-92-31 systemd[2310]: Listening on REST API socket for snapd user session agent.
Jul 16 11:44:15 ip-172-31-92-31 systemd[2310]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Jul 16 11:44:15 ip-172-31-92-31 systemd[2310]: Reached target Sockets.
Jul 16 11:44:15 ip-172-31-92-31 systemd[2310]: Reached target Paths.
Jul 16 11:44:15 ip-172-31-92-31 systemd[2310]: Reached target Basic System.
Jul 16 11:44:15 ip-172-31-92-31 systemd[1]: Started User Manager for UID 1000.
Jul 16 11:44:15 ip-172-31-92-31 systemd[2310]: Reached target Default.
Jul 16 11:44:15 ip-172-31-92-31 systemd[2310]: Startup finished in 65ms.
Jul 16 11:44:26 ip-172-31-92-31 systemd[1]: Started Session 14 of user ubuntu.
